name: Withdraw
main: UniversalRemote\Withdraw
version: "1.0"
api: [3.0.0, 3.3.1]

commands:
 withdraw:
  permission: withdraw.cmd
  description: Withdraw

permissions:
 withdraw.cmd:
  default: true
  description: Withdraw command.
